# Generated by Django 3.2.5 on 2022-04-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='business_books',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='fiction_books',
            field=models.BooleanField(default=False),
        ),
    ]
