# Generated by Django 3.2.5 on 2022-04-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_auto_20220413_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksearch',
            old_name='name_of_book',
            new_name='title',
        ),
    ]
