# Generated by Django 3.2.5 on 2022-04-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_rename_name_of_book_booksearch_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookSearch',
        ),
    ]
