# Generated by Django 3.2.5 on 2022-05-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0013_remove_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(choices=[(0, '0 = Not Watchable'), (1, '1 = Trash'), (2, '2 = Bad'), (3, '3 = Good'), (4, '4 = Very good'), (5, '5 = Perfect')]),
        ),
    ]
